FROM registry.redhat.io/ubi10/go-toolset:10.1 AS builder
USER 0
WORKDIR /go/src/github.com/openshift/secrets-store-csi-driver
COPY . .
RUN make build-e2e-provider

FROM registry.access.redhat.com/ubi10/ubi-minimal:10.1
COPY --from=builder /go/src/github.com/openshift/secrets-store-csi-driver/test/e2eprovider/e2e-provider /e2e-provider

LABEL description="Mock provider for Secrets Store CSI Driver"

ENTRYPOINT ["/e2e-provider"]
